### ISSUE TITLE
there is no output device list for any one ID

### ISSUE THREAD

**Issue by allnode-github** [mockingbirdconsulting/pychirp#15]
I follow the example you said, the program does not report an error, it can be completed normally, but there is no list of output devices. My appid has only 2, each id includes several devices, and there is no output device list for any one ID. It’s unknown for what reason?

**Comment by proffalken** [comment]
Thanks for filing a bug.

Please can you provide example code (*without* your credentials!) so I can see how you are calling the library?

Thanks

**Comment by allnode-github** [comment]
from pyloraserver import loraserver, device

# Setup the connection
cx = loraserver.Loraserver(
        loraserver_url="http://192.168.222.111:8080",
        loraserver_user="user",
        loraserver_pass="psword"
        )

# Connect to the device class
d = device.Devices(loraserver_connection=cx)

# Get all the devices
d.list_all(appid=1).content

**Comment by proffalken** [comment]
@allnode-github - just coming back to this, can you tell me which version of LoRaServer.io you're running? 

I've run the above against our test server and it works well, however we're running an older version on that system as we've not upgraded all of our gateways yet.

**Comment by allnode-github** [comment]
Hello, my version is the latest installation in mid-July, the Lora-app-server version is V3.1, and the other two component versions are also V3.0.

**Comment by proffalken** [comment]
Ah, ok, this could be the issue then, I've not tested against that version.

Give me some time to get a new install up and running and I'll see what I can get working.

**Comment by allnode-github** [comment]
I downloaded your latest version of 0.16 and it works fine. Thank you, I hope this library file is more complete and easy to encode and decode payload.

**Comment by allnode-github** [comment]
I downloaded your latest version of 0.16 and it works fine. Thank you, I hope this library file is more complete and easy to encode and decode payload.

**Comment by allnode-github** [comment]
I downloaded your latest version of 0.16 and it works fine. I hope this library file is more complete, the routines are detailed, and it is more convenient for the payload decoding and so on. thank you very much.

**Comment by proffalken** [comment]
Thanks @allnode-github - I'll close this one off then.

I'm working on the code for managing Applications right now, then I'll move on to Gateways etc.

I hope to have the entire API available through this library eventually, so thanks for the kind words!
